# Generated by Django 5.1.1 on 2024-10-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0002_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
